# action.yml
name: 'Joyce Data Diff Action'
description: 'Roda um diff estatístico em PRs do dbt.'

# Inputs (como o usuário passa informações para nós)
inputs:
  github_token:
    description: 'Token do GitHub para postar comentários.'
    required: true

# Runs (como a Action é executada)
runs:
  using: 'docker'
  image: 'Dockerfile' # Aponta para o Dockerfile que vamos criar