name: 'Joyce Data Diff (v4.0.0 - A Correta)'
description: '[TASK 5+6] Combina a conexão correta (v2) com o parser manual (v2.2.3)'

inputs:
  github_token:
    description: 'Token do GitHub para postar comentários.'
    required: true
  sf_account:
    description: 'A conta Snowflake completa (ex: wemgvex-rf16823.sa-east-1.aws)'
    required: true
  sf_user: { description: 'O usuário do Snowflake', required: true }
  sf_password: { description: 'A senha do Snowflake', required: true }
  sf_role: { description: 'O role', required: true }
  sf_warehouse: { description: 'O warehouse', required: true }
  sf_database: { description: 'O banco de dados', required: true }
  sf_schema:
    description: 'O schema de produção (ex: PROD_SCHEMA)'
    required: true
  dbt_project_dir:
    description: 'O diretório onde o projeto dbt está (ex: dbt_cobaia_project)'
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'