name: 'Joyce Data Diff - dbt Runner'
description: '[TASK 3+4] Clona e roda dbt.'

inputs:
  github_token:
    description: 'Token do GitHub para postar comentários.'
    required: true
  sf_account:
    description: 'A conta Snowflake completa (ex: wemgvex-rf16823.sa-east-1.aws)'
    required: true
  sf_user: { description: 'O usuário do Snowflake', required: true }
  sf_password: { description: 'A senha do Snowflake', required: true }
  sf_role: { description: 'O role', required: true }
  sf_warehouse: { description: 'O warehouse', required: true }
  sf_database: { description: 'O banco de dados', required: true }

  # NOVO INPUT (precisamos do schema de produção)
  sf_schema:
    description: 'O schema de produção (ex: PROD_SCHEMA)'
    required: true

  # NOVO INPUT (para o dbt)
  dbt_project_dir:
    description: 'O diretório onde o projeto dbt está (ex: dbt_cobaia_project)'
    required: false
    default: '.' # Assume que está na raiz

runs:
  using: 'docker'
  image: 'Dockerfile'