name: 'Joyce Data Diff - Teste de Conexão'
description: '[TASK 2] Testa a conexão com o Snowflake.'

inputs:
  sf_account:
    description: 'A conta Snowflake completa (ex: wemgvex-rf16823.sa-east-1.aws)'
    required: true
  sf_user: { description: 'O usuário do Snowflake', required: true }
  sf_password: { description: 'A senha do Snowflake', required: true }
  sf_role: { description: 'O role (ex: ACCOUNTADMIN)', required: true }
  sf_warehouse: { description: 'O warehouse (ex: COMPUTE_WH)', required: true }
  sf_database: { description: 'O banco de dados (ex: DEV_DB)', required: true }

runs:
  using: 'docker'
  image: 'Dockerfile'