# action.yml
name: 'Joyce Data Diff Action'
description: 'Roda um diff estatístico em PRs do dbt para evitar quebras de dados.'

# Define as "entradas" que o usuário vai preencher no workflow
# Por enquanto, vamos só criar um 'placeholder'
inputs:
  github_token:
    description: 'Token do GitHub para postar comentários.'
    required: true

# Define como o Action roda
# Por enquanto, ela não faz nada além de imprimir uma mensagem
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Olá! Eu sou a Action da Joyce e fui acionada!"
        echo "Em breve, eu vou checar seus dados"
      shell: bash